version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:edge
    environment:
      MANIFEST_BRANCH: 'android-10.0'
      # PBRP_BRANCH: '' # OPTIONAL:: If not default 'android-9.0', define other bootable_recovery branch
      VERSION: '3.1.0'
      MAINTAINER: 'Tata Lee @Punkzappa09'
      VENDOR: 'Tecno'
      CODENAME: 'LD7'
      FLAVOR: 'eng'
      TEST_BUILD: 'true'
      # PB_OFFICIAL: "true"
      # EXTRA_CMD: "" # OPTIONAL:: MUST USE DOUBLE-QUOTE
      # PB_ENGLISH: "true" # OPTIONAL:: If you want only English Language
      CHANGELOG: |
        - Initial Build
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
            echo "Ready to Deploy"
            mkdir upload
            export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
            cp out/target/product/${CODENAME}/recovery.img upload/PBRP-${version}-${CODENAME}-$nowTime-Unofficial.img
            cp out/target/product/${CODENAME}/*.img upload/
            cp out/target/product/${CODENAME}/*.zip upload/
            cp out/target/product/${CODENAME}/ramdisk* upload/
            ls -lA upload/
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Latest PBRP Release for $(echo $CODENAME)" -b "PBRP $(echo $version)" -delete twrp_v${version} upload/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
             only: 'pbrp-10.0'
          context: personal-envs
